export 'package:flutter_components_1/screens/alert_screen.dart';
export 'package:flutter_components_1/screens/card_screen.dart';
export 'package:flutter_components_1/screens/home_screen.dart';
export 'package:flutter_components_1/screens/listView1_screen.dart';
export 'package:flutter_components_1/screens/listView2_screen.dart';
export 'package:flutter_components_1/screens/avatar_screen.dart';
export 'package:flutter_components_1/screens/animated_screen.dart';
export 'package:flutter_components_1/screens/inputs_screen.dart';
export 'package:flutter_components_1/screens/slider_screen.dart';